name: movies_app
description: A new Flutter movie application.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/png/movie1.png
    - assets/images/png/movie2.png
    - assets/images/png/movie3.png
    - assets/images/png/movie4.png
    - assets/images/png/movie5.png
    - assets/images/png/movie6.png



