// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoq2csSE8udMoslwEkVJtXo-ICl7B3tH0',
    appId: '1:58733003635:web:ef77f03f9c30cddebb3b06',
    messagingSenderId: '58733003635',
    projectId: 'moviesapp-6b959',
    authDomain: 'moviesapp-6b959.firebaseapp.com',
    storageBucket: 'moviesapp-6b959.firebasestorage.app',
    measurementId: 'G-DQZM2DYCD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVLAr-jpOl_ntldVSUTXmkLIWim-tgnc',
    appId: '1:58733003635:android:7756ac9af2dfbdf0bb3b06',
    messagingSenderId: '58733003635',
    projectId: 'moviesapp-6b959',
    storageBucket: 'moviesapp-6b959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrjs1TDWRTReGegvkI_4C6RF-FZ-Trww',
    appId: '1:58733003635:ios:261d6420d49461f8bb3b06',
    messagingSenderId: '58733003635',
    projectId: 'moviesapp-6b959',
    storageBucket: 'moviesapp-6b959.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrjs1TDWRTReGegvkI_4C6RF-FZ-Trww',
    appId: '1:58733003635:ios:261d6420d49461f8bb3b06',
    messagingSenderId: '58733003635',
    projectId: 'moviesapp-6b959',
    storageBucket: 'moviesapp-6b959.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoq2csSE8udMoslwEkVJtXo-ICl7B3tH0',
    appId: '1:58733003635:web:969e69be98633619bb3b06',
    messagingSenderId: '58733003635',
    projectId: 'moviesapp-6b959',
    authDomain: 'moviesapp-6b959.firebaseapp.com',
    storageBucket: 'moviesapp-6b959.firebasestorage.app',
    measurementId: 'G-SV4RCRZTW9',
  );
}
